/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyectopanaderia;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagLayout;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author joser
 */
public class DialogOpcionesCuenta extends javax.swing.JDialog {

    private Color colorFondo = Color.decode("#EEF4ED");
    private Color colorBtnClaro = Color.decode("#8DA9C4");
    private Color colorBtnOscuro = Color.decode("#13315C");
    private Color colorBorde = Color.decode("#1C5282");
    
    private FramePrincipal principal;
    /**
     * Creates new form DialogOpcionesCuenta
     */
    public DialogOpcionesCuenta(FramePrincipal parent) {
        super(parent, true);
        this.principal = parent;
        this.setUndecorated(true);
        iniciarComponentes();
        this.setUndecorated(true); 
    }

    public void iniciarComponentes(){
        this.setSize(896, 672);
        this.setUndecorated(true); 
        this.setLocationRelativeTo(getParent());

        JPanel panelContenedor = new JPanel(new BorderLayout());
        panelContenedor.setBackground(colorFondo);
        panelContenedor.setBorder(BorderFactory.createLineBorder(colorBorde, 6));


        JPanel panelSuperior = new JPanel(new FlowLayout(FlowLayout.RIGHT, 15, 15));
        panelSuperior.setOpaque(false);

        JButton btnCerrarX = new JButton("X"); 
        btnCerrarX.setFont(new Font("Arial", Font.BOLD, 28));
        btnCerrarX.setForeground(colorBtnOscuro);

        btnCerrarX.setFocusPainted(false);
        btnCerrarX.setBorderPainted(false);
        btnCerrarX.setContentAreaFilled(false);
        btnCerrarX.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        btnCerrarX.addActionListener(e -> this.dispose());

        panelSuperior.add(btnCerrarX);

        JPanel panelCentral = new JPanel(new GridBagLayout());
        panelCentral.setOpaque(false);

        JPanel panelBotones = new JPanel(new FlowLayout(FlowLayout.CENTER, 50, 0)); 
        panelBotones.setOpaque(false);

        JButton btnDesactivar = new JButton("<html><center>Desactivar<br>cuenta</center></html>");
        btnDesactivar.setBackground(colorBtnClaro);
        btnDesactivar.setForeground(Color.WHITE);
        btnDesactivar.setFocusPainted(false);
        btnDesactivar.setFont(new Font("Arial", Font.PLAIN, 32));
        btnDesactivar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnDesactivar.setPreferredSize(new Dimension(300, 130));

        btnDesactivar.addActionListener(e -> {
            //logica desactivar cuenta
            //boton de "estás seguro" (?)
            this.dispose();
        });

        JButton btnCerrar = new JButton("<html><center>Cerrar<br>sesión</center></html>");
        btnCerrar.setBackground(colorBtnOscuro);
        btnCerrar.setForeground(Color.WHITE);
        btnCerrar.setFocusPainted(false);
        btnCerrar.setFont(new Font("Arial", Font.PLAIN, 32));
        btnCerrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnCerrar.setPreferredSize(new Dimension(300, 130));

        btnCerrar.addActionListener(e -> {
            int confirmacion = JOptionPane.showConfirmDialog(this,
                    "¿Estás seguro de que deseas cerrar sesión?",
                    "Confirmar", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                SesionCliente.cerrarSesion();

                this.dispose();

                principal.mostrarPanel(new PanelIndexCliente(principal));
            }
        });

        panelBotones.add(btnDesactivar);
        panelBotones.add(btnCerrar);
        panelCentral.add(panelBotones); 


        panelContenedor.add(panelSuperior, BorderLayout.NORTH);
        panelContenedor.add(panelCentral, BorderLayout.CENTER);

        this.add(panelContenedor);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
