/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyectopanaderia;

import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author joser
 */
public class DialogIniciarSesion extends javax.swing.JDialog {
    private FramePrincipal principal;
    
    //Paleta de colores
    private Color colorHeader = Color.decode("#13315C"); 
    private Color colorFondo = Color.decode("#EEF4ED"); 
    private Color colorPaneles = Color.decode("#8DA9C4"); 
    private Color colorConfirmar = Color.decode("#134074");

    /**
     * Creates new form DialogIniciarSesion
     */
    public DialogIniciarSesion(FramePrincipal principal) {
        super(principal, "Aviso", true);
        this.principal = principal;
        initComponents();
        iniciarComponentes();
    }

    
    public void iniciarComponentes(){
        this.setSize(896, 672);
        this.setUndecorated(true);
        this.setLocationRelativeTo(principal); 

        JPanel panelContenido = new JPanel();
        panelContenido.setLayout(new BoxLayout(panelContenido, BoxLayout.Y_AXIS));
        panelContenido.setBackground(colorFondo);

        panelContenido.setBorder(new LineBorder(colorHeader, 10));

        
        String textoMensaje = "<html><div style='text-align: center;'>"
                + "Parece que no has iniciado<br>sesión!<br>"
                + "Necesitas tener cuenta para<br>acceder a esta opción"
                + "</div></html>";
        
        JLabel lblMensaje = new JLabel(textoMensaje);
        lblMensaje.setFont(new Font("Arial", Font.PLAIN, 45)); // Letra grande
        lblMensaje.setForeground(Color.BLACK);
        lblMensaje.setAlignmentX(Component.CENTER_ALIGNMENT);

        JPanel panelBotones = new JPanel();
        panelBotones.setLayout(new BoxLayout(panelBotones, BoxLayout.X_AXIS));
        panelBotones.setOpaque(false);


        JButton btnCrearCuenta = crearBotonCuadrado("<html><center>Crear<br>cuenta</center></html>", colorPaneles);

        JButton btnIniciarSesion = crearBotonCuadrado("<html><center>Iniciar<br>sesión</center></html>", colorConfirmar);

        btnCrearCuenta.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose(); 
                principal.mostrarPanel(new PanelCrearCuenta(principal)); 
            }
        });

        btnIniciarSesion.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose(); 
                principal.mostrarPanel(new PanelIniciarSesion(principal)); 
            }
        });

        panelBotones.add(Box.createHorizontalGlue());
        panelBotones.add(btnCrearCuenta);
        panelBotones.add(Box.createRigidArea(new Dimension(50, 0))); 
        panelBotones.add(btnIniciarSesion);
        panelBotones.add(Box.createHorizontalGlue());


        panelContenido.add(Box.createVerticalGlue()); 
        panelContenido.add(lblMensaje);
        panelContenido.add(Box.createRigidArea(new Dimension(0, 80))); 
        panelContenido.add(panelBotones);
        panelContenido.add(Box.createVerticalGlue()); 

        this.add(panelContenido);
    }
    
    
    private JButton crearBotonCuadrado(String textoHtml, Color colorFondoBoton) {
        JButton boton = new JButton(textoHtml);
        boton.setBackground(colorFondoBoton);
        boton.setForeground(Color.WHITE);
        boton.setFocusPainted(false);
        boton.setFont(new Font("Arial", Font.PLAIN, 38)); 
        boton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        boton.setPreferredSize(new Dimension(300, 180));
        boton.setMaximumSize(new Dimension(300, 180));
        
        boton.setBorder(BorderFactory.createEmptyBorder()); 
        
        return boton;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
