/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectopanaderia;

import javax.swing.table.DefaultTableModel;
import java.util.List;
import negocio.BOs.IPedidoBO;
import negocio.fabrica.FabricaBOs;
import negocio.DTOs.PedidoEntregaDTO;
import javax.swing.JOptionPane;
import negocio.excepciones.NegocioException;

/**
 *
 * @author golea
 */
public class Entrega_y_Cobro1_1 extends javax.swing.JPanel {

    private final IPedidoBO pedidoBO;
    private int contadorFiltros = 0;

    public Entrega_y_Cobro1_1() {
        initComponents();
        this.pedidoBO = FabricaBOs.obtenerPedidoBO();
        cargarPedidos("");

    }

    private void cambiarPantalla(javax.swing.JPanel nuevoPanel) {
        java.awt.Container parent = this.getParent();

        if (parent != null) {
            parent.remove(this); 
            parent.add(nuevoPanel);

            parent.revalidate();
            parent.repaint();
        }
    }

    private void cargarPedidos(String filtro) {
        try {
            List<PedidoEntregaDTO> pedidos = pedidoBO.buscarPedidosPendientesEntrega(filtro);
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0);

            for (PedidoEntregaDTO pedido : pedidos) {
                Object[] fila = {
                    pedido.getIdPedido(),
                    pedido.getCliente(),
                    pedido.getTipoPedido(),
                    pedido.getMontoTotal(), 
                    pedido.getEstado()
                };
                modelo.addRow(fila);
            }
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void actualizarTablaConLista(List<PedidoEntregaDTO> lista) {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); 

        for (PedidoEntregaDTO p : lista) {
            Object[] fila = {
                p.getIdPedido(),
                p.getCliente(),
                p.getTipoPedido(),
                p.getMontoTotal(),
                p.getEstado()
            };
            modelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnregresar = new javax.swing.JButton();
        btncompletarpedido = new javax.swing.JButton();
        lbltitulo = new javax.swing.JLabel();
        btnfiltrar = new javax.swing.JButton();

        lblNombre.setBackground(new java.awt.Color(141, 169, 196));
        lblNombre.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblNombre.setText("Folio o numero de telefono:");

        txtnombre.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        btnbuscar.setText("buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Tipo Pedido", "Total a Pagar", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnregresar.setText("Regresar");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        btncompletarpedido.setText("Completar pedido");
        btncompletarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncompletarpedidoActionPerformed(evt);
            }
        });

        lbltitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbltitulo.setText("Entrega y Cobro");

        btnfiltrar.setText("filtrar");
        btnfiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btncompletarpedido)
                        .addGap(118, 118, 118))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnbuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnfiltrar)
                        .addGap(0, 26, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnbuscar)
                                .addComponent(btnfiltrar)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 76, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btncompletarpedido)
                            .addComponent(btnregresar))
                        .addGap(17, 17, 17))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        String filtro = txtnombre.getText().trim();
        cargarPedidos(filtro);


    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnregresarActionPerformed

    private void btncompletarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncompletarpedidoActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un pedido de la tabla.");
            return;
        }

        
        int idPedido = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
        String tipo = jTable1.getValueAt(fila, 2).toString();
        String estado = jTable1.getValueAt(fila, 4).toString();

        if (!estado.equalsIgnoreCase("Listo")) {
            JOptionPane.showMessageDialog(this,
                    "No se puede cobrar un pedido en estado: " + estado + ".\nSolo pedidos 'Listo' pueden ser procesados.",
                    "Acción no permitida",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (tipo.equalsIgnoreCase("Express")) {
            cambiarPantalla(new ValidacionPin(idPedido));
        } else {
            cambiarPantalla(new PantallaCobro(idPedido));
        }
    }//GEN-LAST:event_btncompletarpedidoActionPerformed

    private void btnfiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfiltrarActionPerformed
        // TODO add your handling code here:
        try {
            String textoFiltro = txtnombre.getText().trim();
            List<PedidoEntregaDTO> lista = pedidoBO.buscarPedidosPendientesEntrega(textoFiltro);

            contadorFiltros++;
            if (contadorFiltros > 4) {
                contadorFiltros = 1; 
            }
            switch (contadorFiltros) {
                case 1 -> { // Clic 1: Estado "Listo" ascendente
                    lista.sort((p1, p2) -> p1.getEstado().compareTo(p2.getEstado()));
                    JOptionPane.showMessageDialog(this, "Ordenando por: Estado (Listo primero)");
                }
                case 2 -> { // Clic 2: Tipo "Express" ascendente
                    lista.sort((p1, p2) -> p1.getTipoPedido().compareTo(p2.getTipoPedido()));
                    JOptionPane.showMessageDialog(this, "Ordenando por: Pedidos Express");
                }
                case 3 -> { // Clic 3: Tipo "Programado" ascendente
                    // Invertimos el orden para que Programado salga primero si Express era el menor
                    lista.sort((p1, p2) -> p2.getTipoPedido().compareTo(p1.getTipoPedido()));
                    JOptionPane.showMessageDialog(this, "Ordenando por: Pedidos Programados");
                }
                case 4 -> { // Clic 4: ID numérico
                    lista.sort((p1, p2) -> Integer.compare(p1.getIdPedido(), p2.getIdPedido()));
                    JOptionPane.showMessageDialog(this, "Ordenando por: ID (Número)");
                }
            }

            actualizarTablaConLista(lista);

        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error al filtrar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnfiltrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncompletarpedido;
    private javax.swing.JButton btnfiltrar;
    private javax.swing.JButton btnregresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
