/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectopanaderia;

/**
 *
 * @author golea
 */
public class Gestionar_catalogo_de_productos extends javax.swing.JPanel {

    /**
     * Creates new form Gestionar_catalogo_de_productos
     */
    public Gestionar_catalogo_de_productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtdescripcion = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        txtdisponibilidad = new javax.swing.JTextField();
        txttipo = new javax.swing.JTextField();
        btnagregar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnregresarrr = new javax.swing.JButton();
        lbltitulo = new javax.swing.JLabel();
        lbldescripcion = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lbllistadeiingredientes = new javax.swing.JLabel();
        lblprecio = new javax.swing.JLabel();
        lbldisponibilidad = new javax.swing.JLabel();
        lbltipo = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtlistadeingredientes = new javax.swing.JTextField();
        btnregresarrr1 = new javax.swing.JButton();
        txtdescripcion1 = new javax.swing.JTextField();
        txtprecio1 = new javax.swing.JTextField();
        txtdisponibilidad1 = new javax.swing.JTextField();
        txttipo1 = new javax.swing.JTextField();
        lbltitulo1 = new javax.swing.JLabel();
        lbldescripcion1 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lbllistadeiingredientes1 = new javax.swing.JLabel();
        lblprecio1 = new javax.swing.JLabel();
        lbldisponibilidad1 = new javax.swing.JLabel();
        lbltipo1 = new javax.swing.JLabel();
        txtnombre1 = new javax.swing.JTextField();
        txtlistadeingredientes1 = new javax.swing.JTextField();
        btnagregar1 = new javax.swing.JButton();
        btnmodificar1 = new javax.swing.JButton();
        btnregresarrr2 = new javax.swing.JButton();

        txtdescripcion.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        txtprecio.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });

        txtdisponibilidad.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        txttipo.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        btnagregar.setText("Agregar");

        btnmodificar.setText("Modificar");

        btnregresarrr.setText("Regresar");

        lbltitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbltitulo.setText("Inventario de Productos:");

        lbldescripcion.setBackground(new java.awt.Color(141, 169, 196));
        lbldescripcion.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lbldescripcion.setText("Descripcion:");

        lblNombre.setBackground(new java.awt.Color(141, 169, 196));
        lblNombre.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblNombre.setText("Nombre:");

        lbllistadeiingredientes.setBackground(new java.awt.Color(141, 169, 196));
        lbllistadeiingredientes.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lbllistadeiingredientes.setText("Lista de ingredientes:");

        lblprecio.setBackground(new java.awt.Color(141, 169, 196));
        lblprecio.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblprecio.setText("Precio:");

        lbldisponibilidad.setBackground(new java.awt.Color(141, 169, 196));
        lbldisponibilidad.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lbldisponibilidad.setText("Disponibilidad:");

        lbltipo.setBackground(new java.awt.Color(141, 169, 196));
        lbltipo.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lbltipo.setText("Tipo:");

        txtnombre.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        txtlistadeingredientes.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        btnregresarrr1.setText("Regresar");

        txtdescripcion1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        txtprecio1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        txtprecio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecio1ActionPerformed(evt);
            }
        });

        txtdisponibilidad1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        txttipo1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        lbltitulo1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbltitulo1.setText("Inventario de Productos:");

        lbldescripcion1.setBackground(new java.awt.Color(141, 169, 196));
        lbldescripcion1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lbldescripcion1.setText("Descripcion:");

        lblNombre1.setBackground(new java.awt.Color(141, 169, 196));
        lblNombre1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblNombre1.setText("Nombre:");

        lbllistadeiingredientes1.setBackground(new java.awt.Color(141, 169, 196));
        lbllistadeiingredientes1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lbllistadeiingredientes1.setText("Lista de ingredientes:");

        lblprecio1.setBackground(new java.awt.Color(141, 169, 196));
        lblprecio1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblprecio1.setText("Precio:");

        lbldisponibilidad1.setBackground(new java.awt.Color(141, 169, 196));
        lbldisponibilidad1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lbldisponibilidad1.setText("Disponibilidad:");

        lbltipo1.setBackground(new java.awt.Color(141, 169, 196));
        lbltipo1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lbltipo1.setText("Tipo:");

        txtnombre1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        txtlistadeingredientes1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        btnagregar1.setText("Agregar");

        btnmodificar1.setText("Modificar");

        btnregresarrr2.setText("Regresar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(btnregresarrr2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmodificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnagregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbltitulo1)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbltipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblprecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbllistadeiingredientes1)
                                .addComponent(lbldescripcion1)
                                .addComponent(lbldisponibilidad1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtdisponibilidad1)
                                .addComponent(txtdescripcion1)
                                .addComponent(txtlistadeingredientes1)
                                .addComponent(txtnombre1)
                                .addComponent(txtprecio1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txttipo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))))
                    .addGap(14, 14, 14)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnagregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnregresarrr2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(lbltitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNombre1)
                        .addComponent(txtnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbllistadeiingredientes1)
                        .addComponent(txtlistadeingredientes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbldescripcion1)
                        .addComponent(txtdescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblprecio1)
                        .addComponent(txtprecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbldisponibilidad1)
                        .addComponent(txtdisponibilidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbltipo1)
                        .addComponent(txttipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(115, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioActionPerformed

    private void txtprecio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecio1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnagregar1;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnmodificar1;
    private javax.swing.JButton btnregresarrr;
    private javax.swing.JButton btnregresarrr1;
    private javax.swing.JButton btnregresarrr2;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lbldescripcion;
    private javax.swing.JLabel lbldescripcion1;
    private javax.swing.JLabel lbldisponibilidad;
    private javax.swing.JLabel lbldisponibilidad1;
    private javax.swing.JLabel lbllistadeiingredientes;
    private javax.swing.JLabel lbllistadeiingredientes1;
    private javax.swing.JLabel lblprecio;
    private javax.swing.JLabel lblprecio1;
    private javax.swing.JLabel lbltipo;
    private javax.swing.JLabel lbltipo1;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lbltitulo1;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtdescripcion1;
    private javax.swing.JTextField txtdisponibilidad;
    private javax.swing.JTextField txtdisponibilidad1;
    private javax.swing.JTextField txtlistadeingredientes;
    private javax.swing.JTextField txtlistadeingredientes1;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnombre1;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtprecio1;
    private javax.swing.JTextField txttipo;
    private javax.swing.JTextField txttipo1;
    // End of variables declaration//GEN-END:variables
}
