/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectopanaderia;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.BOs.IProductoBO;
import negocio.excepciones.NegocioException;
import negocio.fabrica.FabricaBOs;
import persistencia.dominio.Producto;

/**
 *
 * @author golea
 */
public class Gestionar_catalogo_de_productos_1 extends javax.swing.JPanel {

    private IProductoBO productoBO = FabricaBOs.obtenerProductoBO();
    private List<Producto> listaProductos;

    /**
     * Creates new form Gestionar_catalogo_de_productos
     */
    public Gestionar_catalogo_de_productos_1() {
        initComponents();

        cargarTablaProductos();
    }

    private void cargarTablaProductos() {
        DefaultTableModel modelo = (DefaultTableModel) Tablaproductos.getModel();
        modelo.setRowCount(0);

        try {
            this.listaProductos = productoBO.listarProductos();

            if (this.listaProductos != null) {
                for (Producto p : this.listaProductos) {
                    Object[] fila = {
                        p.getId(),
                        p.getNombre(),
                        p.getTipo(),
                        p.getDescripcion(),
                        p.getPrecio(),
                        p.getEstado()
                    };
                    modelo.addRow(fila);
                }
            }
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar productos: " + e.getMessage());
        }
    }

    private void limpiarCampos() {
        txtnombre1.setText("");
        txttipo1.setText("");
        txtdescripcion1.setText("");
        txtprecio1.setText("");
        txtdisponibilidad1.setText("");
        Tablaproductos.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtdescripcion = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        txtdisponibilidad = new javax.swing.JTextField();
        txttipo = new javax.swing.JTextField();
        btnagregar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnregresarrr = new javax.swing.JButton();
        lbltitulo = new javax.swing.JLabel();
        lbldescripcion = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lbllistadeiingredientes = new javax.swing.JLabel();
        lblprecio = new javax.swing.JLabel();
        lbldisponibilidad = new javax.swing.JLabel();
        lbltipo = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtlistadeingredientes = new javax.swing.JTextField();
        btnregresarrr1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtdescripcion1 = new javax.swing.JTextField();
        txtprecio1 = new javax.swing.JTextField();
        txtdisponibilidad1 = new javax.swing.JTextField();
        txttipo1 = new javax.swing.JTextField();
        lbltitulo1 = new javax.swing.JLabel();
        lbldescripcion1 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblprecio1 = new javax.swing.JLabel();
        lbldisponibilidad1 = new javax.swing.JLabel();
        lbltipo1 = new javax.swing.JLabel();
        txtnombre1 = new javax.swing.JTextField();
        btnagregar1 = new javax.swing.JButton();
        btnmodificar1 = new javax.swing.JButton();
        btnregresarrr2 = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tablaproductos = new javax.swing.JTable();

        txtdescripcion.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        txtprecio.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });

        txtdisponibilidad.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        txttipo.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        btnagregar.setText("Agregar");

        btnmodificar.setText("Modificar");

        btnregresarrr.setText("Regresar");

        lbltitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbltitulo.setText("Inventario de Productos:");

        lbldescripcion.setBackground(new java.awt.Color(141, 169, 196));
        lbldescripcion.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lbldescripcion.setText("Descripcion:");

        lblNombre.setBackground(new java.awt.Color(141, 169, 196));
        lblNombre.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblNombre.setText("Nombre:");

        lbllistadeiingredientes.setBackground(new java.awt.Color(141, 169, 196));
        lbllistadeiingredientes.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lbllistadeiingredientes.setText("Lista de ingredientes:");

        lblprecio.setBackground(new java.awt.Color(141, 169, 196));
        lblprecio.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblprecio.setText("Precio:");

        lbldisponibilidad.setBackground(new java.awt.Color(141, 169, 196));
        lbldisponibilidad.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lbldisponibilidad.setText("Disponibilidad:");

        lbltipo.setBackground(new java.awt.Color(141, 169, 196));
        lbltipo.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lbltipo.setText("Tipo:");

        txtnombre.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        txtlistadeingredientes.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        btnregresarrr1.setText("Regresar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        txtdescripcion1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        txtprecio1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        txtprecio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecio1ActionPerformed(evt);
            }
        });

        txtdisponibilidad1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        txttipo1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        lbltitulo1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbltitulo1.setText("Inventario de Productos:");

        lbldescripcion1.setBackground(new java.awt.Color(141, 169, 196));
        lbldescripcion1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lbldescripcion1.setText("Descripcion:");

        lblNombre1.setBackground(new java.awt.Color(141, 169, 196));
        lblNombre1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblNombre1.setText("Nombre:");

        lblprecio1.setBackground(new java.awt.Color(141, 169, 196));
        lblprecio1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblprecio1.setText("Precio:");

        lbldisponibilidad1.setBackground(new java.awt.Color(141, 169, 196));
        lbldisponibilidad1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lbldisponibilidad1.setText("Disponibilidad:");

        lbltipo1.setBackground(new java.awt.Color(141, 169, 196));
        lbltipo1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lbltipo1.setText("Tipo:");

        txtnombre1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        btnagregar1.setText("Agregar");
        btnagregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregar1ActionPerformed(evt);
            }
        });

        btnmodificar1.setText("Modificar");
        btnmodificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificar1ActionPerformed(evt);
            }
        });

        btnregresarrr2.setText("Regresar");

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        Tablaproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, "", null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Productos", "Nombre", "Tipo", "Descripcion", "Precio", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Tablaproductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnregresarrr2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnmodificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnagregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblprecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldescripcion1)
                            .addComponent(lbldisponibilidad1)
                            .addComponent(lbltipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txttipo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(txtdisponibilidad1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtprecio1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtdescripcion1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbltitulo1)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(258, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(txtnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldescripcion1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblprecio1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdisponibilidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldisponibilidad1))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltipo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnagregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnregresarrr2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(lbltitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addComponent(lblNombre1)
                    .addContainerGap(376, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioActionPerformed

    private void txtprecio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecio1ActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed

     
        int filaSeleccionada = Tablaproductos.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un producto de la tabla.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
          
            Producto p = this.listaProductos.get(filaSeleccionada);

            txtnombre1.setText(p.getNombre());
            txttipo1.setText(p.getTipo());
            txtdescripcion1.setText(p.getDescripcion());
            txtprecio1.setText(String.valueOf(p.getPrecio()));
            txtdisponibilidad1.setText(p.getEstado());

            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al recuperar los datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnmodificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificar1ActionPerformed
        
        int fila = Tablaproductos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla primero.");
            return;
        }

        try {
            int id = (int) Tablaproductos.getValueAt(fila, 0);

            Producto p = new Producto();
            p.setId(id);
            p.setNombre(txtnombre1.getText());
            p.setTipo(txttipo1.getText());
            p.setDescripcion(txtdescripcion1.getText());
            p.setPrecio(Float.parseFloat(txtprecio1.getText()));
            p.setEstado(txtdisponibilidad1.getText());

         
            productoBO.actualizar(p);

            JOptionPane.showMessageDialog(this, "Producto actualizado con éxito.");

            cargarTablaProductos();

            limpiarCampos();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
        }

    }//GEN-LAST:event_btnmodificar1ActionPerformed

    private void btnagregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregar1ActionPerformed
        // TODO add your handling code here:
        try {
            
            if (txtnombre1.getText().isEmpty() || txtprecio1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor llena los campos obligatorios (Nombre y Precio).");
                return;
            }

            Producto nuevoProducto = new Producto();
            nuevoProducto.setNombre(txtnombre1.getText());
            nuevoProducto.setTipo(txttipo1.getText()); 
            nuevoProducto.setDescripcion(txtdescripcion1.getText());
            nuevoProducto.setPrecio(Float.parseFloat(txtprecio1.getText()));
            nuevoProducto.setEstado(txtdisponibilidad1.getText());

            productoBO.agregar(nuevoProducto);

            JOptionPane.showMessageDialog(this, "Producto agregado correctamente.");

            cargarTablaProductos();
            limpiarCampos(); 
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio debe ser un número válido.", "Error de formato", JOptionPane.ERROR_MESSAGE);
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error de Negocio", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnagregar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablaproductos;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnagregar1;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnmodificar1;
    private javax.swing.JButton btnregresarrr;
    private javax.swing.JButton btnregresarrr1;
    private javax.swing.JButton btnregresarrr2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lbldescripcion;
    private javax.swing.JLabel lbldescripcion1;
    private javax.swing.JLabel lbldisponibilidad;
    private javax.swing.JLabel lbldisponibilidad1;
    private javax.swing.JLabel lbllistadeiingredientes;
    private javax.swing.JLabel lblprecio;
    private javax.swing.JLabel lblprecio1;
    private javax.swing.JLabel lbltipo;
    private javax.swing.JLabel lbltipo1;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lbltitulo1;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtdescripcion1;
    private javax.swing.JTextField txtdisponibilidad;
    private javax.swing.JTextField txtdisponibilidad1;
    private javax.swing.JTextField txtlistadeingredientes;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnombre1;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtprecio1;
    private javax.swing.JTextField txttipo;
    private javax.swing.JTextField txttipo1;
    // End of variables declaration//GEN-END:variables
}
