/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectopanaderia;

/**
 *
 * @author golea
 */
public class interfaz_admin extends javax.swing.JFrame {

    /**
     * Creates new form interfaz_admin
     */
    public interfaz_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnentregaycobro = new javax.swing.JButton();
        btnpreparaciondepedidos = new javax.swing.JButton();
        btncatalogodeproductos = new javax.swing.JButton();
        btnregresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("Selecciona la Operacion a Realizar");

        btnentregaycobro.setText("Entrega y Cobro");
        btnentregaycobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentregaycobroActionPerformed(evt);
            }
        });

        btnpreparaciondepedidos.setText("Gestión Preparación de Pedidos");
        btnpreparaciondepedidos.setToolTipText("");
        btnpreparaciondepedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreparaciondepedidosActionPerformed(evt);
            }
        });

        btncatalogodeproductos.setText("Gestionar Catálogo de Productos");
        btncatalogodeproductos.setToolTipText("");
        btncatalogodeproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncatalogodeproductosActionPerformed(evt);
            }
        });

        btnregresar.setText("Regresar");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btncatalogodeproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnpreparaciondepedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnentregaycobro, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnpreparaciondepedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncatalogodeproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnentregaycobro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpreparaciondepedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreparaciondepedidosActionPerformed
        // TODO add your handling code here:
        Gestion_preparacion_de_pedidos panelPreparacion = new Gestion_preparacion_de_pedidos();

        // Limpiar el contenido actual del frame
        this.getContentPane().removeAll();

        // Cambiar el Layout si es necesario para que el panel ocupe todo el espacio
        this.setLayout(new java.awt.BorderLayout());
        this.add(panelPreparacion, java.awt.BorderLayout.CENTER);

        // CRITICO: Refrescar la interfaz para que los cambios sean visibles
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnpreparaciondepedidosActionPerformed

    private void btncatalogodeproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncatalogodeproductosActionPerformed
        // TODO add your handling code here:
        Gestionar_catalogo_de_productos PanelCatalogo = new Gestionar_catalogo_de_productos();

        // Limpiar el contenido actual del frame
        this.getContentPane().removeAll();

        // Cambiar el Layout si es necesario para que el panel ocupe todo el espacio
        this.setLayout(new java.awt.BorderLayout());
        this.add(PanelCatalogo, java.awt.BorderLayout.CENTER);

        // CRITICO: Refrescar la interfaz para que los cambios sean visibles
        this.revalidate();
        this.repaint();
                                                  

    }//GEN-LAST:event_btncatalogodeproductosActionPerformed

    private void btnentregaycobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentregaycobroActionPerformed
        // TODO add your handling code here:
        Entrega_y_Cobro1 panelEntrega = new Entrega_y_Cobro1();

        // Limpiar el contenido actual del frame
        this.getContentPane().removeAll();

        // Cambiar el Layout si es necesario para que el panel ocupe todo el espacio
        this.setLayout(new java.awt.BorderLayout());
        this.add(panelEntrega, java.awt.BorderLayout.CENTER);

        // CRITICO: Refrescar la interfaz para que los cambios sean visibles
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnentregaycobroActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        // TODO add your handling code here:

        Interfaz_admin1 In = new Interfaz_admin1();

        // Limpiar el contenido actual del frame
        this.getContentPane().removeAll();

        // Cambiar el Layout si es necesario para que el panel ocupe todo el espacio
        this.setLayout(new java.awt.BorderLayout());
        this.add(In, java.awt.BorderLayout.CENTER);

        // CRITICO: Refrescar la interfaz para que los cambios sean visibles
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnregresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncatalogodeproductos;
    private javax.swing.JButton btnentregaycobro;
    private javax.swing.JButton btnpreparaciondepedidos;
    private javax.swing.JButton btnregresar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
