/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectopanaderia;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Cursor;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author golea
 */
public class Interfaz_admin1 extends javax.swing.JPanel {

    private Color colorHeader = Color.decode("#13315C");
    private Color colorFondo = Color.decode("#EEF4ED");
    private Color colorPaneles = Color.decode("#8DA9C4");
    private Color colorConfirmar = Color.decode("#134074");
    private FramePrincipal principal;

    public Interfaz_admin1(FramePrincipal principal) {
        this.principal = principal;
        initComponents();
        disenoManual();
    }

    private void disenoManual() {
        // Configuración del Panel Principal
        this.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        this.setBackground(colorFondo);

        // --- HEADER ---
        JPanel panelHeader = new JPanel();
        panelHeader.setLayout(new BoxLayout(panelHeader, BoxLayout.X_AXIS));
        panelHeader.setBackground(colorHeader);
        panelHeader.setMaximumSize(new Dimension(1024, 120));
        panelHeader.setPreferredSize(new Dimension(1024, 120));
        panelHeader.setBorder(new EmptyBorder(0, 50, 0, 0));

        JLabel lblTituloHeader = new JLabel("Panel de Administración");
        lblTituloHeader.setFont(new Font("SansSerif", Font.PLAIN, 36));
        lblTituloHeader.setForeground(Color.WHITE);
        panelHeader.add(lblTituloHeader);

        // --- CONTENIDO CENTRAL ---
        JPanel mainContent = new JPanel();
        mainContent.setLayout(new BoxLayout(mainContent, BoxLayout.Y_AXIS));
        mainContent.setOpaque(false);
        mainContent.setBorder(new EmptyBorder(40, 100, 40, 100));

        // Título de instrucción
        jLabel1.setText("Selecciona la operación a realizar:");
        jLabel1.setFont(new Font("SansSerif", Font.BOLD, 22));
        jLabel1.setForeground(colorHeader);
        jLabel1.setAlignmentX(CENTER_ALIGNMENT);

        // Estilizar Botones como "Tarjetas"
        estilizarBotonMenu(btnpreparaciondepedidos);
        estilizarBotonMenu(btncatalogodeproductos);
        estilizarBotonMenu(btnentregaycobro);

        // Botón Regresar (Estilo secundario)
        btnregresar.setFont(new Font("SansSerif", Font.PLAIN, 18));
        btnregresar.setAlignmentX(CENTER_ALIGNMENT);

        // Ensamblar Main Content
        mainContent.add(jLabel1);
        mainContent.add(Box.createRigidArea(new Dimension(0, 30)));
        mainContent.add(btnpreparaciondepedidos);
        mainContent.add(Box.createRigidArea(new Dimension(0, 15)));
        mainContent.add(btncatalogodeproductos);
        mainContent.add(Box.createRigidArea(new Dimension(0, 15)));
        mainContent.add(btnentregaycobro);
        mainContent.add(Box.createRigidArea(new Dimension(0, 40)));
        mainContent.add(btnregresar);

        // Limpiar y Reconstruir
        this.removeAll();
        this.add(panelHeader);
        this.add(mainContent);
        this.revalidate();
        this.repaint();
    }

    private void estilizarBotonMenu(JButton btn) {
        btn.setFont(new Font("SansSerif", Font.BOLD, 20));
        btn.setBackground(colorPaneles);
        btn.setForeground(Color.WHITE);
        btn.setMaximumSize(new Dimension(600, 80)); // Botones anchos tipo "barra"
        btn.setPreferredSize(new Dimension(600, 80));
        btn.setFocusPainted(false);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btn.setAlignmentX(CENTER_ALIGNMENT);
        // Efecto visual de borde
        btn.setBorder(javax.swing.BorderFactory.createLineBorder(colorHeader, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnentregaycobro = new javax.swing.JButton();
        btnpreparaciondepedidos = new javax.swing.JButton();
        btncatalogodeproductos = new javax.swing.JButton();
        btnregresar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("Selecciona la Operacion a Realizar");

        btnentregaycobro.setText("Entrega y Cobro");
        btnentregaycobro.setBorderPainted(false);
        btnentregaycobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentregaycobroActionPerformed(evt);
            }
        });

        btnpreparaciondepedidos.setText("Gestión Preparación de Pedidos");
        btnpreparaciondepedidos.setToolTipText("");
        btnpreparaciondepedidos.setBorderPainted(false);
        btnpreparaciondepedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreparaciondepedidosActionPerformed(evt);
            }
        });

        btncatalogodeproductos.setText("Gestionar Catálogo de Productos");
        btncatalogodeproductos.setToolTipText("");
        btncatalogodeproductos.setBorderPainted(false);
        btncatalogodeproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncatalogodeproductosActionPerformed(evt);
            }
        });

        btnregresar.setText("Regresar");
        btnregresar.setBorderPainted(false);
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btncatalogodeproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnpreparaciondepedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnentregaycobro, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnpreparaciondepedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncatalogodeproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnentregaycobro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnpreparaciondepedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreparaciondepedidosActionPerformed
        // TODO add your handling code here:
        btnpreparaciondepedidos.addActionListener(e -> {
            principal.mostrarPanel(new Gestion_preparacion_de_pedidos(principal));
        });

    }//GEN-LAST:event_btnpreparaciondepedidosActionPerformed

    private void btncatalogodeproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncatalogodeproductosActionPerformed
        // TODO add your handling code here:
        btncatalogodeproductos.addActionListener(e -> {
            principal.mostrarPanel(new Gestionar_catalogo_de_productos(principal));
        });
    }//GEN-LAST:event_btncatalogodeproductosActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        // TODO add your handling code here:
        btnregresar.addActionListener(e -> {
            principal.mostrarPanel(new PanelAdminUsuario(principal));
        });
    }//GEN-LAST:event_btnregresarActionPerformed

    private void btnentregaycobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentregaycobroActionPerformed
        // TODO add your handling code here:
        btnentregaycobro.addActionListener(e -> {
            principal.mostrarPanel(new Entrega_y_Cobro1(principal));
        });
    }//GEN-LAST:event_btnentregaycobroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncatalogodeproductos;
    private javax.swing.JButton btnentregaycobro;
    private javax.swing.JButton btnpreparaciondepedidos;
    private javax.swing.JButton btnregresar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
