/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectopanaderia;

/**
 *
 * @author golea
 */
public class PanerAdminLogin extends javax.swing.JPanel {

    /**
     * Creates new form PanerAdminLogin
     */
    private FramePrincipal principal;

    public PanerAdminLogin(FramePrincipal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btningresar = new javax.swing.JButton();
        BtnRegresar = new javax.swing.JButton();
        lblIngresarcorreo = new javax.swing.JLabel();
        lblIngresarCorreo = new javax.swing.JLabel();
        txtingresarcorreo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtingresarcontrasena = new javax.swing.JTextField();
        lbltitulo = new javax.swing.JLabel();

        Btningresar.setText("Ingresar");
        Btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtningresarActionPerformed(evt);
            }
        });

        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });

        lblIngresarCorreo.setText("Ingresar Correo:");

        jLabel1.setText("Ingresar contraseña:");

        lbltitulo.setText("Ingresar Como Empleado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtingresarcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(BtnRegresar)
                                .addGap(187, 187, 187)
                                .addComponent(Btningresar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtingresarcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblIngresarcorreo))
                            .addComponent(lblIngresarCorreo))
                        .addContainerGap(260, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lbltitulo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(lblIngresarcorreo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lbltitulo)
                        .addGap(39, 39, 39)
                        .addComponent(lblIngresarCorreo)
                        .addGap(18, 18, 18)
                        .addComponent(txtingresarcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtingresarcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btningresar)
                    .addComponent(BtnRegresar))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        // TODO add your handling code here:
        principal.mostrarPanel(new PanelAdminUsuario(principal));


    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void BtningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtningresarActionPerformed
        // TODO add your handling code here:
        String correo = txtingresarcorreo.getText().trim();
        String password = txtingresarcontrasena.getText().trim();

        if (correo.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Campos obligatorios", "Aviso", 0);
            return;
        }

        try {
            // LLAMADA REAL A LA BASE DE DATOS
            persistencia.DAOs.IEmpleadoDAO empleadoDAO = persistencia.fabrica.FabricaDAOs.obtenerEmpleadoDAO();
            boolean esValido = empleadoDAO.validarCredenciales(correo, password);

            if (esValido) {
                javax.swing.JOptionPane.showMessageDialog(this, "Acceso Correcto");
                principal.mostrarPanel(new Interfaz_admin1(principal));
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Correo o contraseña inválidos", "Error", 0);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error de conexión: " + e.getMessage());
        }
    }//GEN-LAST:event_BtningresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JButton Btningresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblIngresarCorreo;
    private javax.swing.JLabel lblIngresarcorreo;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTextField txtingresarcontrasena;
    private javax.swing.JTextField txtingresarcorreo;
    // End of variables declaration//GEN-END:variables
}
