/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectopanaderia;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import negocio.BOs.IPedidoBO;
import negocio.DTOs.PedidoEntregaDTO;
import negocio.excepciones.NegocioException;
import negocio.fabrica.FabricaBOs;
import persistencia.dominio.Cupon;

/**
 *
 * @author golea
 */
public class PantallaCobro extends javax.swing.JPanel {

    private int idPedido;
    private final IPedidoBO pedidoBO;
    private float montoTotal = 0; 

    public PantallaCobro(int idPedido) {
        this.idPedido = idPedido;
        this.pedidoBO = FabricaBOs.obtenerPedidoBO();
        initComponents();
        obtenerMontoDePedido();
        cargarCupones();
    }

    private void obtenerMontoDePedido() {
        try {
            List<PedidoEntregaDTO> lista = pedidoBO.buscarPedidosPendientesEntrega(String.valueOf(idPedido));

            for (PedidoEntregaDTO p : lista) {
                if (p.getIdPedido() == idPedido) {
                    this.montoTotal = p.getMontoTotal();
                    lbldescuento.setText(String.format("%.2f", montoTotal));
                    break;
                }
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar el monto: " + ex.getMessage());
        }
    }

    private void cargarCupones() {
        try {
            List<Cupon> cupones = pedidoBO.obtenerCuponesVigentes();

            DefaultComboBoxModel model = new DefaultComboBoxModel();
            model.addElement("Selecciona un cupón...");

            for (Cupon c : cupones) {
                model.addElement(c);
            }

            Descuentoscuponera.setModel(model);

        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "No se pudieron cargar los cupones: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbldescuento = new javax.swing.JLabel();
        lbltitulo = new javax.swing.JLabel();
        txtMontoaintroducir = new javax.swing.JTextField();
        lblIntroduceelmonto = new javax.swing.JLabel();
        lblmontoapagar1 = new javax.swing.JLabel();
        btnpagar = new javax.swing.JButton();
        btnregresar1 = new javax.swing.JButton();
        lbltextodescuento = new javax.swing.JLabel();
        lblmostrarmontoapagar1 = new javax.swing.JLabel();
        Descuentoscuponera = new javax.swing.JComboBox();

        lbldescuento.setBackground(new java.awt.Color(141, 169, 196));
        lbldescuento.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lbldescuento.setText("00");

        lbltitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbltitulo.setText("Pago");

        txtMontoaintroducir.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        txtMontoaintroducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoaintroducirActionPerformed(evt);
            }
        });

        lblIntroduceelmonto.setBackground(new java.awt.Color(141, 169, 196));
        lblIntroduceelmonto.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblIntroduceelmonto.setText("Introduce el monto:");

        lblmontoapagar1.setBackground(new java.awt.Color(141, 169, 196));
        lblmontoapagar1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblmontoapagar1.setText("Monto a pagar:");

        btnpagar.setText("Pagar");
        btnpagar.setActionCommand("Regresar");
        btnpagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpagarActionPerformed(evt);
            }
        });

        btnregresar1.setText("regresar");
        btnregresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresar1ActionPerformed(evt);
            }
        });

        lbltextodescuento.setBackground(new java.awt.Color(141, 169, 196));
        lbltextodescuento.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lbltextodescuento.setText("Descuento:");

        lblmostrarmontoapagar1.setBackground(new java.awt.Color(141, 169, 196));
        lblmostrarmontoapagar1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblmostrarmontoapagar1.setText("00");

        Descuentoscuponera.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Descuentos" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblmontoapagar1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblmostrarmontoapagar1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbltextodescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblIntroduceelmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMontoaintroducir, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbldescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(btnregresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(btnpagar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Descuentoscuponera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmontoapagar1)
                    .addComponent(lblmostrarmontoapagar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltextodescuento)
                    .addComponent(lbldescuento))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntroduceelmonto)
                    .addComponent(txtMontoaintroducir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Descuentoscuponera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnregresar1)
                    .addComponent(btnpagar))
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoaintroducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoaintroducirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoaintroducirActionPerformed

    private void btnpagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpagarActionPerformed
        // TODO add your handling code here:
        try {
            float pagoRecibido = Float.parseFloat(txtMontoaintroducir.getText().trim());

            if (pagoRecibido < montoTotal) {
                JOptionPane.showMessageDialog(this, "Dinero insuficiente.");
                return;
            }

            pedidoBO.procesarEntrega(idPedido, "Efectivo");

            JOptionPane.showMessageDialog(this, "Pago procesado. Cambio: $" + (pagoRecibido - montoTotal));

            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un monto válido.");
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnpagarActionPerformed

    private void btnregresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresar1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnregresar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Descuentoscuponera;
    private javax.swing.JButton btnpagar;
    private javax.swing.JButton btnregresar1;
    private javax.swing.JLabel lblIntroduceelmonto;
    private javax.swing.JLabel lbldescuento;
    private javax.swing.JLabel lblmontoapagar1;
    private javax.swing.JLabel lblmostrarmontoapagar1;
    private javax.swing.JLabel lbltextodescuento;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTextField txtMontoaintroducir;
    // End of variables declaration//GEN-END:variables
}
