/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectopanaderia;

import javax.swing.JOptionPane;
import negocio.BOs.IPedidoBO;
import negocio.excepciones.NegocioException;
import negocio.fabrica.FabricaBOs;

/**
 *
 * @author golea
 */
public class ValidacionPin extends javax.swing.JPanel {

    private int idPedido;
    private final IPedidoBO pedidoBO;
   
    public ValidacionPin(int idPedido) {
        this.idPedido = idPedido;
        this.pedidoBO = FabricaBOs.obtenerPedidoBO(); 
        initComponents();
        this.Iblidmostrar.setText(String.valueOf(idPedido));

    }
    
    private void cambiarPantalla(javax.swing.JPanel nuevoPanel) {
        java.awt.Container parent = this.getParent();

        if (parent != null) {
            parent.remove(this); 
            parent.add(nuevoPanel); 

            parent.revalidate();
            parent.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        btnvalidarpin = new javax.swing.JButton();
        btnregresar1 = new javax.swing.JButton();
        lblNombre1 = new javax.swing.JLabel();
        Iblidmostrar = new javax.swing.JLabel();

        lbltitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbltitulo.setText("Validar pin");

        lblNombre.setBackground(new java.awt.Color(141, 169, 196));
        lblNombre.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblNombre.setText("Validar Pin:");

        txtnombre.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        btnvalidarpin.setText("Validar Pin");
        btnvalidarpin.setActionCommand("Regresar");
        btnvalidarpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvalidarpinActionPerformed(evt);
            }
        });

        btnregresar1.setText("Regresar");
        btnregresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresar1ActionPerformed(evt);
            }
        });

        lblNombre1.setBackground(new java.awt.Color(141, 169, 196));
        lblNombre1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblNombre1.setText("ID:");

        Iblidmostrar.setBackground(new java.awt.Color(141, 169, 196));
        Iblidmostrar.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        Iblidmostrar.setText("-----");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnvalidarpin))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombre1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Iblidmostrar)
                                .addGap(115, 115, 115)))))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(btnregresar1)
                    .addContainerGap(190, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre1)
                    .addComponent(Iblidmostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(18, 18, 18)
                .addComponent(btnvalidarpin)
                .addGap(65, 65, 65))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(212, Short.MAX_VALUE)
                    .addComponent(btnregresar1)
                    .addGap(64, 64, 64)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnvalidarpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvalidarpinActionPerformed
        // TODO add your handling code here:
       
    String pinIngresado = txtnombre.getText().trim();

    if (pinIngresado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese el PIN de seguridad.");
        return;
    }

    try {
        
        pedidoBO.validarPinExpress(idPedido, pinIngresado);

        JOptionPane.showMessageDialog(this, "PIN Correcto. Procediendo al cobro.");
        cambiarPantalla(new PantallaCobro(idPedido));

    } catch (NegocioException ex) {
        JOptionPane.showMessageDialog(this, "El PIN es incorrecto", "Error de Validación", JOptionPane.ERROR_MESSAGE);
        txtnombre.setText(""); 
        txtnombre.requestFocus();
    }


    }//GEN-LAST:event_btnvalidarpinActionPerformed

    private void btnregresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresar1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnregresar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Iblidmostrar;
    private javax.swing.JButton btnregresar1;
    private javax.swing.JButton btnvalidarpin;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
